# Generated by Django 2.2 on 2021-04-29 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_article_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(related_name='articles', to='controller.User'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ManyToManyField(related_name='searches', to='controller.User'),
        ),
    ]
