# Generated by Django 2.2 on 2021-04-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210429_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='content',
            new_name='keyword',
        ),
    ]
